# Generated by Django 4.2.30 on 2026-07-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='custom_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
